version: '3.7'

services:
  db:
    image: mysql
#    image: arm64v8/mysql:oracle
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: service_db
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - 3306:3306
